server:
  port: ${SERVER.PORT:54000}
spring:
  application:
    name: ${SPRING.APPLICATION.NAME:shortlink-server}
  cloud:
    nacos:
      discovery:
        group: DEV_GROUP
        server-addr: localhost:58848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.130.171:53306/xingchi_framework?useSSL=false&serverTimezone=UTC
    username: root
    password: xy19981123..

eureka:
  client:
    service-url:
      defaultZone: http://localhost:58090/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

xingchi:
  short:
    link:
      domain: https://runaway.cn/
